name: mdgen
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - aom=3.4.0
  - astunparse=1.6.3
  - biotite=0.38.0
  - blosc=1.21.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.12.0
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.4.1
  - cpuonly=2.0
  - dm-tree=0.1.8
  - expat=2.6.4
  - fair-esm=1.0.2
  - ffmpeg=5.1.0
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.6
  - hdf5=1.14.0
  - icu=73.2
  - idna=3.10
  - jinja2=3.1.5
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=19.1.7
  - libdeflate=1.20
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.3
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran5=13.2.0
  - libiconv=1.18
  - libidn2=2.3.7
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnghttp2=1.51.0
  - libopenblas=0.3.24
  - libpng=1.6.43
  - libprotobuf=3.21.12
  - libsqlite=3.46.0
  - libssh2=1.10.0
  - libtasn1=4.20.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.50.0
  - libvpx=1.11.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzlib=1.2.13
  - lightning-utilities=0.12.0
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mdtraj=1.10.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.2.1
  - nomkl=1.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - olefile=0.47
  - opencl-headers=2024.10.24
  - openh264=2.3.0
  - openmm=8.2.0
  - openssl=1.1.1w
  - packaging=24.2
  - pip=25.0.1
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pysocks=1.7.1
  - pytables=3.8.0
  - python=3.9.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.9
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - pytz=2025.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - scipy=1.13.1
  - setuptools=75.8.2
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.46.0
  - svt-av1=1.2.0
  - tk=8.6.13
  - torchaudio=2.0.2
  - torchmetrics=1.6.1
  - torchvision=0.15.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - anndata==0.10.9
      - annotated-types==0.7.0
      - appnope==0.1.4
      - argcomplete==3.5.3
      - array-api-compat==1.11
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.1.0
      - biopython==1.79
      - boto==2.49.0
      - cachetools==5.5.2
      - cffi==1.17.1
      - clean-fid==0.1.35
      - click==8.1.8
      - comm==0.2.2
      - contourpy==1.2.1
      - crcmod==1.7
      - cryptography==43.0.3
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.2.1
      - diffusers==0.32.2
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fasteners==0.19
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gcs-oauth2-boto-plugin==3.2
      - get-annotations==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-reauth==0.1.1
      - grpcio==1.70.0
      - gsutil==5.33
      - h5py==3.13.0
      - httplib2==0.20.4
      - huggingface-hub==0.29.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - legacy-api-wrap==1.4.1
      - lightning-bolts==0.7.0
      - llvmlite==0.43.0
      - markdown==3.7
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.7
      - monotonic==1.6
      - multidict==6.1.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - numba==0.60.0
      - oauth2client==4.1.3
      - pandas==1.5.3
      - parso==0.8.4
      - pastel==0.2.1
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==9.5.0
      - platformdirs==4.3.6
      - poethepoet==0.10.0
      - pot==0.9.5
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==5.29.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyopenssl==24.2.1
      - pyparsing==3.0.9
      - pytorch-lightning==1.9.5
      - pyu2f==0.1.5
      - pyzmq==26.2.1
      - regex==2024.11.6
      - retry-decorator==1.1.1
      - rsa==4.7.2
      - safetensors==0.5.3
      - scanpy==1.10.3
      - scikit-learn==1.6.1
      - scprep==1.2.3
      - seaborn==0.13.2
      - sentry-sdk==2.22.0
      - session-info==1.0.0
      - setproctitle==1.3.5
      - smmap==5.0.2
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tomlkit==0.13.2
      - torch==2.0.1
      - torchcde==0.2.5
      - torchcfm==1.0.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchsde==0.2.6
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - wandb==0.19.7
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
      - zipp==3.21.0

